---
output: 
    md_document:
        variant: markdown_github
---

# Other effects of sleep fragmentation

### Authors: 
Peter Kamerman, Fiona Baker & Stella Iacovides

### Date of last 'knit'
`r format(Sys.time(), "%B %d, %Y")`

****

## Load required packages and set chunk options
```{r LoadPackages, include = FALSE}
# Load packages
library(ggplot2)
library(scales)
library(grid)
library(cowplot)
library(knitr)
library(PMCMR) # Pairwise post-hoc for Friedman test
library(coin) # Alternative Friedman test (used for von Frey)
library(readr)
library(dplyr)
library(tidyr)
library(svglite)

# Colour-blind palette
cb.palette <- c("#006BA4", "#C85200", "#595959")


# set seed
set.seed(123)

# knitr chunk options
opts_chunk$set(echo = TRUE,
               warning = FALSE,
               message = FALSE,
               fig.path = './figures/',
               fig.width = 7,
               fig.height = 7,
               fig.align = 'center',
               dev = c('svg', 'pdf'),
               tidy = FALSE)
```

## Load data
```{r importData}
data <- read_csv('./data/other.csv')
# PILL data as number (count) of questionniare items rated as 
# mild or moderate-to-severe
data_pill <- read_csv('./data/pill-data.csv') 
```

### Quick look
```{r lookData}
# dim(data)
# names(data)
# head(data)
# tail(data)
glimpse(data)
summary(data)
```

### Process data
```{r processData}
# Convert id and period to factors
data <- data %>%
    mutate(id = factor(id), 
           period = factor(period))
# Divide data into subsets for analysis
## Touch sensitivity before and after ischaemia
vonfrey <- data %>%
    select(id, period, vF.before_mN, vf.during_mN)
## Pin-prick sensitivity before ischaemia
pinprick <- data %>%
    select(id, period, pin.prick_mN)
## Profile of Mood State (POMS) before sleep (poms.evening), and after sleep (poms.morning)
poms <- data %>%
    select(id, period, poms.morning, poms.evening)
## Sleep quality after sleep (0-100mm VAS)
sleep.qual <- data %>%
    select(id, period, sleep.quality)
## Morning vigilance after sleep (0-100mm VAS)
morning.vig <- data %>%
    select(id, period, morning.vigilance)
```

## Data analysis
### Sleep quality
```{r sleepQuality}
# Plot
ggplot(sleep.qual, 
       aes(x = period,
           y = sleep.quality,
           colour = period,
           fill = period)) +
    geom_boxplot(fatten = 4,
                 colour = '#666666',
                 fill = '#666666',
                 alpha = 0.5) +
    labs(x = '\nIntervention',
         y = 'Sleep quality (0-100mm VAS)\n',
         title = 'Sleep quality\n') +
    scale_y_continuous(limits = c(0, 100), expand = c(0,0)) +
    scale_x_discrete(labels = c('Baseline\nnight', 
                                'Fragmentation\nnight 1',
                                'Fragmentation\nnight 2')) +
    theme_cowplot() +
    theme(legend.position = 'none',
          axis.text = element_text(size = 18),
          axis.title = element_text(size = 18),
          plot.title = element_text(size = 18))
# Friedman test
friedman.test(sleep.quality ~ period | id, data = sleep.qual)
head(sleep.qual)
# Pairwise posthoc 
posthoc.friedman.conover.test(y = sleep.qual$sleep.quality, 
                              groups = sleep.qual$period, 
                              blocks = sleep.qual$id, 
                              p.adjust.method = 'holm')
```

### Morning vigilance
```{r morningVigilance}
# Plot
ggplot(morning.vig, 
       aes(x = period,
           y = morning.vigilance,
           colour = period,
           fill = period)) +
    geom_boxplot(fatten = 4,
                 colour = '#666666',
                 fill = '#666666',
                 alpha = 0.5) +
    labs(x = '\nIntervention',
         y = 'Morning vigilance (0-100mm VAS)\n',
         title = 'Morning vigilance\n') +
    scale_y_continuous(limits = c(0, 100), expand = c(0,0)) +
    scale_x_discrete(labels = c('Baseline\nnight', 
                                'Fragmentation\nnight 1',
                                'Fragmentation\nnight 2')) +
    theme_cowplot() +
    theme(legend.position = 'none',
          axis.text = element_text(size = 18),
          axis.title = element_text(size = 18),
          plot.title = element_text(size = 18))
# Friedman test
friedman.test(morning.vigilance ~ period | id, data = morning.vig)
# Pairwise posthoc 
posthoc.friedman.conover.test(y = morning.vig$morning.vigilance,
                              groups = morning.vig$period,
                              blocks = morning.vig$id, 
                              p.adjust.method = 'holm')
```

### Pin-prick
```{r pinPrick}
# Plot
ggplot(pinprick, 
       aes(x = period,
           y = pin.prick_mN,
           colour = period,
           fill = period)) +
    geom_boxplot(fatten = 4,
                 colour = '#666666',
                 fill = '#666666',
                 alpha = 0.5) +
    labs(x = '\nIntervention',
         y = 'Pin-prick threshold (mN)\n',
         title = 'Pin-prick theshold\n') +
    scale_y_continuous(limits = c(0, 550), expand = c(0,0)) +
    scale_x_discrete(labels = c('Baseline\nnight', 
                                'Fragmentation\nnight 1',
                                'Fragmentation\nnight 2')) +
    theme_cowplot() +
    theme(legend.position = 'none',
          axis.text = element_text(size = 18),
          axis.title = element_text(size = 18),
          plot.title = element_text(size = 18))
# Friedman test
friedman.test(pin.prick_mN ~ period | id, data = pinprick)
# Pairwise posthoc 
posthoc.friedman.conover.test(y = pinprick$pin.prick_mN,
                              groups = pinprick$period,
                              blocks = pinprick$id, 
                              p.adjust.method = 'holm')
```

### Profile of Mood States
```{r poms}
# Plot
poms_plot <- poms %>%
    group_by(id, period) %>%
    gather(key = time, 
           value = score, 
           poms.morning, 
           poms.evening)

ggplot(poms_plot, 
       aes(x = period,
           y = score,
           colour = time,
           fill = time)) +
    geom_boxplot(fatten = 4, alpha = 0.5) +
    labs(x = '\nIntervention',
         y = 'Profile of Mood States (POMS) score\n',
         title = 'Profile of Mood States (POMS)\n') +
    scale_y_continuous(limits = c(75, 125), 
                       expand = c(0,0)) +
    scale_x_discrete(labels = c('Baseline\nnight', 
                                'Fragmentation\nnight 1',
                                'Fragmentation\nnight 2')) +
    scale_fill_manual(name = 'Time',
                      labels = c('Evening', 'Morning'),
                      values = cb.palette) +
    scale_colour_manual(name = 'Time',
                      labels = c('Evening', 'Morning'),
                      values = cb.palette) +
    theme_cowplot() +
    theme(legend.position = c(0.9, 0.075),
          legend.text = element_text(size = 18),
          legend.title = element_text(size = 18),
          legend.background = element_rect(fill = 'gray90'),
          axis.text = element_text(size = 18),
          axis.title = element_text(size = 18),
          plot.title = element_text(size = 18))
# Friedman test - Evening
friedman.test(poms.evening ~ period | id, data = poms)
# Pairwise posthoc - Evening
posthoc.friedman.conover.test(y = poms$poms.evening,
                              groups = poms$period,
                              blocks = poms$id,
                              p.adjust.method = 'holm')
# Friedman test - Morning
friedman.test(poms.morning ~ period | id, data = poms)
# Pairwise posthoc - Morning
posthoc.friedman.conover.test(y = poms$poms.morning,
                              groups = poms$period,
                              blocks = poms$id,
                              p.adjust.method = 'holm')
```

### von Frey
```{r vfrey}
# von Frey was performed to assess whether fragmentation affected touch sensitivity,
# and to confirm whether the tourniquet indiced hypoaesthesia.

# Plot
vf_plot <- vonfrey %>%
    group_by(id, period) %>%
    gather(key = time,
           value = score, 
           vF.before_mN, 
           vf.during_mN)

ggplot(vf_plot, 
       aes(x = period,
           y = score,
           colour = time,
           fill = time)) +
    geom_boxplot(fatten = 4, alpha = 0.5) +
    labs(x = '\nIntervention',
         y = 'von Frey threshold (mN)\n',
         title = 'von Frey threshold\n') +
    scale_y_continuous(limits = c(0, 65), 
                       expand = c(0,0)) +
    scale_x_discrete(labels = c('Baseline\nnight', 
                                'Fragmentation\nnight 1',
                                'Fragmentation\nnight 2')) +
    scale_fill_manual(name = 'Time',
                      labels = c('Evening', 'Morning'),
                      values = cb.palette) +
    scale_colour_manual(name = 'Time',
                        labels = c('Evening', 'Morning'),
                        values = cb.palette) +
    theme_cowplot() +
    theme(legend.position = c(0.12, 0.90),
          legend.text = element_text(size = 18),
          legend.title = element_text(size = 18),
          legend.background = element_rect(fill = 'gray90'),
          axis.text = element_text(size = 18),
          axis.title = element_text(size = 18),
          plot.title = element_text(size = 18))
# Friedman test - Before ischaemia
friedman_test(vF.before_mN ~ period | id, data = vonfrey, 
             distribution = approximate(B = 10000))
# Wilcoxon signed rank test - Before vs during ischaemia
## Baseline
vf_base <- vf_plot %>%
    ungroup() %>%
    filter(period == 'baseline') %>%
    mutate(period = factor(period),
           time = factor(time)) 
vf_base_w <- wilcox_test(score ~ time | id, data = vf_base)
vf_base_w
## Fragmentation night 1
vf_frag1 <- vf_plot %>%
    ungroup() %>%
    filter(period == 'fragmentation1') %>%
    mutate(period = factor(period),
           time = factor(time)) 
vf_frag1_w <- wilcox_test(score ~ time | id, data = vf_base)
vf_frag1_w
## Fragmentation night 2
vf_frag2 <- vf_plot %>%
    ungroup() %>%
    filter(period == 'fragmentation2') %>%
    mutate(period = factor(period),
           time = factor(time)) 
vf_frag2_w <- wilcox_test(score ~ time | id, data = vf_base)
vf_frag2_w
## Holm correction
vf_holm <- c(pvalue(vf_base_w), pvalue(vf_frag1_w), pvalue(vf_frag2_w))
matrix(round(p.adjust(vf_holm, method = 'holm'), 5), 
       ncol = 3, nrow = 1, 
       dimnames = list(c('p-value'),
                       c('baseline', 'fragmentation 1', 'fragmentation 2')))
```

### PILL
```{r pillCount}
# PILL Questionniare consists of 10 questions, each rated on a 
# 5-point Likert, which we condensed as follows:
# (0 = not at all, 1-2: mild, 3-4: moderate-to-severe)

# Process data
pill_plot <- data_pill %>%
    # Add 'not at all' data 'counts_zero' (total = 10 questions)
    mutate(counts_zero = 10 - (counts_mild + counts_mod_severe)) %>%
    gather(severity, count, -id, -period, -time) %>%
    # Order 'count' categories
    mutate(severity = factor(severity, 
                             levels = c('counts_zero', 
                                        'counts_mild', 
                                        'counts_mod_severe'),
                             ordered = TRUE)) %>%
    arrange(id, period, time, severity)

# Plot
ggplot(pill_plot, 
       aes(x = period,
           y = count,
           colour = severity,
           fill = severity)) +
    geom_boxplot(fatten = 4, alpha = 0.5) +
    facet_grid(time~.) +
    labs(x = '\nIntervention',
         y = 'PILL item counts\n',
         title = 'PILL item count data\n') +
    scale_y_discrete(limits = c(0, 10),
                     breaks = c(0, 2, 4, 6, 8, 10),
                     labels = c(0, 2, 4, 6, 8, 10),
                     expand = c(0,0)) +
    scale_x_discrete(labels = c('Baseline\nnight', 
                                'Fragmentation\nnight 1',
                                'Fragmentation\nnight 2')) +
    scale_fill_manual(name = 'Severity: ',
                      labels = c('None at all',
                                 'Mild', 
                                 'Moderate-to-severe'),
                      values = cb.palette) +
    scale_colour_manual(name = 'Severity: ',
                      labels = c('None at all',
                                 'Mild', 
                                 'Moderate-to-severe'),
                      values = cb.palette) +
    theme_cowplot() +
    theme(legend.position = 'bottom',
          legend.text = element_text(size = 18),
          legend.title = element_text(size = 18),
          legend.background = element_rect(fill = 'gray90'),
          axis.text = element_text(size = 18),
          axis.title = element_text(size = 18),
          plot.title = element_text(size = 18),
          panel.margin.y = unit(3, units = "lines"))

# Friedman test - Evening (none)
pill_evening_zero <- pill_plot %>%
    filter(time == 'evening' & severity == 'counts_zero')
foo <- friedman.test(count ~ period | id, data = pill_evening_zero)
foo
# Friedman test - Morning (none)
pill_morning_zero <- pill_plot %>%
    filter(time == 'morning' & severity == 'counts_zero')
bar <- friedman.test(count ~ period | id, data = pill_morning_zero)
bar
# Friedman test - Evening (mild)
pill_evening_mild <- pill_plot %>%
    filter(time == 'evening' & severity == 'counts_mild')
baz <- friedman.test(count ~ period | id, data = pill_evening_mild)
baz
# Friedman test - Morning (mild)
pill_morning_mild <- pill_plot %>%
    filter(time == 'morning' & severity == 'counts_mild')
qux <- friedman.test(count ~ period | id, data = pill_morning_mild)
qux
# Friedman test - Evening (mod-severe)
pill_evening_mod_severe <- pill_plot %>%
    filter(time == 'evening' & severity == 'counts_mod_severe')
fred <- friedman.test(count ~ period | id, 
                      data = pill_evening_mod_severe)
fred
# Friedman test - Morning (mod-severe)
pill_morning_mod_severe <- pill_plot %>%
    filter(time == 'morning' & severity == 'counts_mod_severe')
barney <- friedman.test(count ~ period | id,
                        data = pill_morning_mod_severe)
barney
# Family-wise correction for multiple comparisons
p_values <- c(zero_evening = foo$p.value,
              zero_morning = bar$p.value,
              mild_evening = baz$p.value,
              mild_morning = qux$p.value,
              mod_severe_evening = fred$p.value,
              mod_severe_morning = barney$p.value)
p.adjust(p_values, method = 'holm')
```

## Session information
```{r sessionInfo}
sessionInfo()
```